#!/bin/bash
# Generate .dev.vars.test files for each worker from environment variables
# Called by CI workflow after environment variables are set by GitHub Actions
#
# Required environment variables:
#   DATABASE_URL - Neon database connection string
#   DB_METHOD - Database connection method (NEON_BRANCH)
#   BETTER_AUTH_SECRET - Auth secret (optional, has default)
#   STRIPE_SECRET_KEY - Stripe API key (for ecom-api, content-api)
#   STRIPE_WEBHOOK_SECRET_BOOKING - Stripe webhook secret
#   R2_ACCOUNT_ID - Cloudflare R2 account ID
#   R2_ACCESS_KEY_ID - R2 access key
#   R2_SECRET_ACCESS_KEY - R2 secret key
#   R2_BUCKET_MEDIA - R2 media bucket name

set -e

echo "Generating .dev.vars.test files for workers..."

WORKERS=("auth" "content-api" "identity-api" "organization-api" "notifications-api" "ecom-api" "admin-api" "media-api")

for worker in "${WORKERS[@]}"; do
  VARS_FILE="workers/${worker}/.dev.vars.test"
  echo "  Generating ${VARS_FILE}..."

  # Base variables for all workers
  cat > "${VARS_FILE}" << EOF
# Generated by CI workflow - do not edit manually
DATABASE_URL=${DATABASE_URL}
DB_METHOD=${DB_METHOD:-NEON_BRANCH}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-test-secret-key-minimum-32-characters-long}
BETTER_AUTH_URL=http://localhost:42069
AUTH_TRUST_HOST=true
WORKER_SHARED_SECRET=${WORKER_SHARED_SECRET:-${BETTER_AUTH_SECRET:-test-secret-key-minimum-32-characters-long}}
EOF

  # Add Stripe and R2 variables for workers that need them
  case "${worker}" in
    "ecom-api")
      cat >> "${VARS_FILE}" << EOF
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET_BOOKING=${STRIPE_WEBHOOK_SECRET_BOOKING}
EOF
      ;;
    "content-api")
      cat >> "${VARS_FILE}" << EOF
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET_BOOKING=${STRIPE_WEBHOOK_SECRET_BOOKING}
R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
R2_BUCKET_MEDIA=${R2_BUCKET_MEDIA}
EOF
      ;;
    "media-api")
      cat >> "${VARS_FILE}" << EOF
RUNPOD_API_KEY=${RUNPOD_API_KEY}
RUNPOD_ENDPOINT_ID=${RUNPOD_ENDPOINT_ID}
RUNPOD_WEBHOOK_SECRET=${RUNPOD_WEBHOOK_SECRET}
RUNPOD_API_URL=${RUNPOD_API_URL:-http://localhost:4002/internal/mock-runpod}
B2_ENDPOINT=${B2_ENDPOINT}
B2_KEY_ID=${B2_KEY_ID}
B2_APP_KEY=${B2_APP_KEY}
B2_BUCKET=${B2_BUCKET}
EOF
      ;;
  esac
done

echo "All .dev.vars.test files generated successfully"
