version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: codex-postgres-test
    environment:
      POSTGRES_USER: codex_test
      POSTGRES_PASSWORD: codex_test_password
      POSTGRES_DB: codex_test
    ports:
      - '5433:5432'
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U codex_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data:
