import type { BrandPreset } from './types';

/**
 * Built-in brand presets.
 *
 * Each preset provides a complete set of brand values that produce
 * a visually distinct result when applied. The CSS engine (org-brand.css)
 * derives the full palette from these inputs via OKLCH relative colors.
 */
export type PresetCategory =
  | 'Professional'
  | 'Creative'
  | 'Bold'
  | 'Minimal'
  | 'Organic'
  | 'Tech'
  | 'Luxury'
  | 'Playful'
  | 'Atmospheric';

export interface CategorizedPreset extends BrandPreset {
  category: PresetCategory;
}

export const BRAND_PRESETS: readonly CategorizedPreset[] = [
  // ─── Professional ───────────────────────────────────────────────────
  {
    id: 'corporate',
    name: 'Corporate',
    category: 'Professional',
    description: 'Professional and trustworthy — tight spacing',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'topo',
      'shader-topo-line-count': '40',
      'shader-topo-speed': '0.3',
      'heading-color': '#1E3A5F',
      'hero-title-blend': 'normal',
      'hero-title-color': '#ffffff',
      'hero-cta-bg': '#1E40AF',
      'hero-cta-text': '#ffffff',
      'card-hover-scale': '1.01',
      'card-image-hover-scale': '1.02',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#1E40AF',
      secondaryColor: '#4B5563',
      accentColor: '#059669',
      backgroundColor: null,
      fontBody: 'Source Sans 3',
      fontHeading: 'Source Sans 3',
      radius: 0.375,
      density: 0.95,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },
  {
    id: 'executive',
    name: 'Executive',
    category: 'Professional',
    description: 'Refined and authoritative — dark navy, gold accent',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'silk',
      'shader-silk-speed': '0.3',
      'shader-silk-sheen': '0.7',
      'heading-color': '#1E293B',
      'hero-title-blend': 'normal',
      'hero-title-color': '#ffffff',
      'hero-cta-bg': '#D97706',
      'hero-cta-text': '#1E293B',
      'glass-tint': '#D97706',
      'card-hover-scale': '1.015',
      'card-image-hover-scale': '1.03',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#1E293B',
      secondaryColor: '#64748B',
      accentColor: '#D97706',
      backgroundColor: null,
      fontBody: 'DM Sans',
      fontHeading: 'DM Sans',
      radius: 0.25,
      density: 0.9,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },
  {
    id: 'consulting',
    name: 'Consulting',
    category: 'Professional',
    description: 'Clean, approachable, expert — teal primary',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'clouds',
      'shader-clouds-speed': '0.4',
      'hero-cta-bg': '#0D9488',
      'hero-cta-text': '#ffffff',
      'card-hover-scale': '1.02',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#0D9488',
      secondaryColor: '#6B7280',
      accentColor: '#F97316',
      backgroundColor: null,
      fontBody: 'Inter',
      fontHeading: 'Inter',
      radius: 0.5,
      density: 1,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },

  // ─── Creative ───────────────────────────────────────────────────────
  {
    id: 'vibrant',
    name: 'Vibrant',
    category: 'Creative',
    description: 'Bold and energetic — rounded, saturated colors',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'glow',
      'shader-glow-count': '8',
      'shader-glow-size': '0.6',
      'heading-color': '#7C3AED',
      'hero-glass-tint': '#EC4899',
      'hero-border-tint': '#EC4899',
      'glass-tint': '#EC4899',
      'card-hover-scale': '1.04',
      'card-image-hover-scale': '1.08',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#7C3AED',
      secondaryColor: '#EC4899',
      accentColor: '#F59E0B',
      backgroundColor: null,
      fontBody: 'Poppins',
      fontHeading: 'Poppins',
      radius: 0.75,
      density: 1,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'Creative',
    description: 'Warm gradient feel — coral, amber, earthy',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'nebula',
      'shader-nebula-speed': '0.3',
      'shader-nebula-density': '0.6',
      'hero-glass-tint': '#FBBF24',
      'hero-border-tint': '#FBBF24',
      'glass-tint': '#FBBF24',
      'card-hover-scale': '1.03',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#E11D48',
      secondaryColor: '#F97316',
      accentColor: '#FBBF24',
      backgroundColor: null,
      fontBody: 'Nunito',
      fontHeading: 'Nunito',
      radius: 1,
      density: 1.05,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    category: 'Creative',
    description: 'Cool and calming — deep blues to aqua',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'caustic',
      'shader-caustic-speed': '0.5',
      'shader-caustic-brightness': '0.6',
      'hero-glass-tint': '#34D399',
      'hero-border-tint': '#0891B2',
      'glass-tint': '#34D399',
      'card-hover-scale': '1.02',
    },
    values: {
      primaryColor: '#0284C7',
      secondaryColor: '#0891B2',
      accentColor: '#34D399',
      backgroundColor: null,
      fontBody: 'Outfit',
      fontHeading: 'Outfit',
      radius: 0.75,
      density: 1,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },

  // ─── Bold ───────────────────────────────────────────────────────────
  {
    id: 'dark',
    name: 'Dark',
    category: 'Bold',
    description: 'Moody and modern — dark surface, light accents',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'ether',
      'shader-intensity': '0.7',
      'heading-color': '#818CF8',
      'hero-title-blend': 'normal',
      'hero-title-color': '#818CF8',
      'hero-glass-tint': '#818CF8',
      'glass-tint': '#A78BFA',
      'card-hover-scale': '1.03',
    },
    values: {
      primaryColor: '#818CF8',
      secondaryColor: '#A78BFA',
      accentColor: '#FBBF24',
      backgroundColor: '#0F172A',
      fontBody: 'DM Sans',
      fontHeading: 'DM Sans',
      radius: 0.5,
      density: 1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#A78BFA',
        backgroundColor: '#0B1120',
      },
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'Bold',
    description: 'High contrast, electric — black background, neon green',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'flux',
      'shader-flux-line-density': '0.7',
      'shader-flux-speed': '0.5',
      'heading-color': '#22D3EE',
      'hero-title-blend': 'normal',
      'hero-title-color': '#22D3EE',
      'hero-glass-tint': '#A3E635',
      'hero-border-tint': '#22D3EE',
      'player-text': '#22D3EE',
      'glass-tint': '#A3E635',
      'card-hover-scale': '1.05',
      'card-image-hover-scale': '1.1',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#22D3EE',
      secondaryColor: '#A3E635',
      accentColor: '#F472B6',
      backgroundColor: '#09090B',
      fontBody: 'Space Grotesk',
      fontHeading: 'Space Grotesk',
      radius: 0.25,
      density: 0.95,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#67E8F9',
        backgroundColor: '#050505',
      },
    },
  },
  {
    id: 'ember',
    name: 'Ember',
    category: 'Bold',
    description: 'Fiery intensity — deep red, warm surface',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'lava',
      'shader-lava-glow': '0.7',
      'shader-lava-speed': '0.4',
      'heading-color': '#DC2626',
      'hero-glass-tint': '#EA580C',
      'hero-border-tint': '#DC2626',
      'glass-tint': '#EA580C',
      'card-hover-scale': '1.03',
    },
    values: {
      primaryColor: '#DC2626',
      secondaryColor: '#EA580C',
      accentColor: '#FCD34D',
      backgroundColor: '#1C1917',
      fontBody: 'Rubik',
      fontHeading: 'Rubik',
      radius: 0.375,
      density: 1,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },

  // ─── Minimal ────────────────────────────────────────────────────────
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'Minimal',
    description: 'Clean and understated — sharp corners, neutral palette',
    heroLayout: 'default',
    tokenOverrides: {
      'card-hover-scale': '1.0',
      'card-image-hover-scale': '1.0',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#1A1A1A',
      secondaryColor: '#737373',
      accentColor: null,
      backgroundColor: null,
      fontBody: null,
      fontHeading: null,
      radius: 0,
      density: 1,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'Minimal',
    description: 'Warm, editorial — off-white, soft radius',
    heroLayout: 'default',
    tokenOverrides: {
      'heading-color': '#78716C',
      'glass-tint': '#D6D3D1',
      'card-hover-scale': '1.015',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#78716C',
      secondaryColor: '#A8A29E',
      accentColor: '#B45309',
      backgroundColor: '#FAFAF9',
      fontBody: 'Lora',
      fontHeading: 'Lora',
      radius: 0.5,
      density: 1.1,
      heroLayout: 'default',
      darkOverrides: null,
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    category: 'Minimal',
    description: 'Pure black and white — maximum contrast, no colour',
    heroLayout: 'default',
    tokenOverrides: {
      'heading-color': '#000000',
      'hero-title-blend': 'normal',
      'hero-title-color': '#000000',
      'hero-cta-bg': '#000000',
      'hero-cta-text': '#ffffff',
      'card-hover-scale': '1.01',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#000000',
      secondaryColor: '#525252',
      accentColor: null,
      backgroundColor: '#FFFFFF',
      fontBody: null,
      fontHeading: null,
      radius: 0,
      density: 0.95,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#ffffff',
        backgroundColor: '#0A0A0A',
      },
    },
  },

  // ─── Organic ────────────────────────────────────────────────────────
  {
    id: 'forest',
    name: 'Forest',
    category: 'Organic',
    description: 'Deep greens and earthy tones — nature-inspired calm',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'growth',
      'shader-growth-speed': '0.3',
      'shader-growth-glow': '0.4',
      'heading-color': '#14532D',
      'hero-glass-tint': '#65A30D',
      'hero-border-tint': '#65A30D',
      'glass-tint': '#65A30D',
      'card-hover-scale': '1.02',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#14532D',
      secondaryColor: '#854D0E',
      accentColor: '#65A30D',
      backgroundColor: '#FAFDF7',
      fontBody: 'Bitter',
      fontHeading: 'Bitter',
      radius: 0.75,
      density: 1.05,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#22C55E',
        backgroundColor: '#0C1A0F',
      },
    },
  },
  {
    id: 'desert',
    name: 'Desert',
    category: 'Organic',
    description: 'Warm sand and terracotta — sun-baked, expansive',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'waves',
      'shader-waves-speed': '0.3',
      'shader-waves-chop': '0.2',
      'heading-color': '#78350F',
      'hero-glass-tint': '#D97706',
      'hero-border-tint': '#D97706',
      'glass-tint': '#D2B48C',
      'card-hover-scale': '1.02',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#A0522D',
      secondaryColor: '#92400E',
      accentColor: '#D97706',
      backgroundColor: '#FDF8F0',
      fontBody: 'Libre Baskerville',
      fontHeading: 'Libre Baskerville',
      radius: 0.5,
      density: 1.1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#D2956B',
        backgroundColor: '#1A120B',
      },
    },
  },
  {
    id: 'bloom',
    name: 'Bloom',
    category: 'Organic',
    description: 'Soft pinks and botanical warmth — delicate, flourishing',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'pollen',
      'shader-pollen-density': '0.5',
      'shader-pollen-drift': '0.3',
      'heading-color': '#9D174D',
      'hero-glass-tint': '#F472B6',
      'hero-border-tint': '#F9A8D4',
      'glass-tint': '#F9A8D4',
      'card-hover-scale': '1.02',
      'card-image-hover-scale': '1.04',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#BE185D',
      secondaryColor: '#DB2777',
      accentColor: '#F472B6',
      backgroundColor: '#FDF2F8',
      fontBody: 'Nunito',
      fontHeading: 'Playfair Display',
      radius: 1,
      density: 1.05,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#F472B6',
        backgroundColor: '#1A0A14',
      },
    },
  },

  // ─── Tech ──────────────────────────────────────────────────────────
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'Tech',
    description: 'Hacker aesthetic — black background, green phosphor glow',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'spore',
      'shader-spore-decay': '0.95',
      'heading-color': '#4ADE80',
      'hero-title-blend': 'normal',
      'hero-title-color': '#4ADE80',
      'hero-glass-tint': '#4ADE80',
      'hero-border-tint': '#4ADE80',
      'player-text': '#4ADE80',
      'glass-tint': '#4ADE80',
      'card-hover-scale': '1.01',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#4ADE80',
      secondaryColor: '#86EFAC',
      accentColor: '#FDE047',
      backgroundColor: '#0A0A0A',
      fontBody: 'JetBrains Mono',
      fontHeading: 'JetBrains Mono',
      radius: 0.125,
      density: 0.9,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#4ADE80',
        backgroundColor: '#050505',
      },
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    category: 'Tech',
    description: 'Technical precision — blueprint blue, structured grid',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'gyroid',
      'shader-gyroid-speed': '0.3',
      'shader-gyroid-density': '0.5',
      'heading-color': '#1E3A8A',
      'hero-cta-bg': '#1E3A8A',
      'hero-cta-text': '#ffffff',
      'glass-tint': '#BFDBFE',
      'card-hover-scale': '1.015',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#1E3A8A',
      secondaryColor: '#3B82F6',
      accentColor: '#60A5FA',
      backgroundColor: '#EFF6FF',
      fontBody: 'IBM Plex Sans',
      fontHeading: 'IBM Plex Sans',
      radius: 0.25,
      density: 0.9,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#60A5FA',
        backgroundColor: '#0A1628',
      },
    },
  },
  {
    id: 'gradient',
    name: 'Gradient',
    category: 'Tech',
    description: 'Purple-to-cyan energy — modern SaaS, fluid motion',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'flow',
      'shader-flow-curl': '0.6',
      'shader-flow-contrast': '0.5',
      'heading-color': '#7C3AED',
      'hero-glass-tint': '#06B6D4',
      'hero-border-tint': '#8B5CF6',
      'glass-tint': '#06B6D4',
      'card-hover-scale': '1.04',
      'card-image-hover-scale': '1.08',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#8B5CF6',
      secondaryColor: '#06B6D4',
      accentColor: '#F472B6',
      backgroundColor: null,
      fontBody: 'Inter',
      fontHeading: 'Inter',
      radius: 0.75,
      density: 1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#A78BFA',
      },
    },
  },

  // ─── Luxury ─────────────────────────────────────────────────────────
  {
    id: 'onyx',
    name: 'Onyx',
    category: 'Luxury',
    description: 'Premium dark — gold accents on near-black, crystalline',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'bismuth',
      'shader-bismuth-iridescence': '0.7',
      'shader-bismuth-speed': '0.3',
      'heading-color': '#B8860B',
      'hero-title-blend': 'normal',
      'hero-title-color': '#D4A843',
      'hero-glass-tint': '#B8860B',
      'hero-border-tint': '#D4A843',
      'player-text': '#D4A843',
      'glass-tint': '#B8860B',
      'card-hover-scale': '1.01',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#B8860B',
      secondaryColor: '#D4A843',
      accentColor: '#F5DEB3',
      backgroundColor: '#0C0A09',
      fontBody: 'DM Sans',
      fontHeading: 'Playfair Display',
      radius: 0.25,
      density: 0.95,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#D4A843',
        backgroundColor: '#080706',
      },
    },
  },
  {
    id: 'marble',
    name: 'Marble',
    category: 'Luxury',
    description:
      'Refined simplicity — off-white, charcoal veins, pearl shimmer',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'pearl',
      'shader-pearl-speed': '0.3',
      'shader-pearl-fresnel': '0.6',
      'heading-color': '#292524',
      'glass-tint': '#D6D3D1',
      'card-hover-scale': '1.015',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#292524',
      secondaryColor: '#57534E',
      accentColor: '#A8A29E',
      backgroundColor: '#FAFAF9',
      fontBody: 'Cormorant Garamond',
      fontHeading: 'Cormorant Garamond',
      radius: 0.375,
      density: 1.05,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#D6D3D1',
        backgroundColor: '#1C1917',
      },
    },
  },
  {
    id: 'velvet',
    name: 'Velvet',
    category: 'Luxury',
    description: 'Deep purple opulence — lavender highlights, silk texture',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'silk',
      'shader-silk-speed': '0.3',
      'shader-silk-sheen': '0.8',
      'shader-silk-softness': '0.6',
      'heading-color': '#C4B5FD',
      'hero-title-blend': 'normal',
      'hero-title-color': '#C4B5FD',
      'hero-glass-tint': '#A78BFA',
      'hero-border-tint': '#8B5CF6',
      'glass-tint': '#A78BFA',
      'card-hover-scale': '1.02',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#A78BFA',
      secondaryColor: '#8B5CF6',
      accentColor: '#C4B5FD',
      backgroundColor: '#1E1B4B',
      fontBody: 'DM Sans',
      fontHeading: 'Cormorant Garamond',
      radius: 0.5,
      density: 1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#C4B5FD',
        backgroundColor: '#0F0D2E',
      },
    },
  },

  // ─── Playful ────────────────────────────────────────────────────────
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    category: 'Playful',
    description: 'Sugar rush — hot pink, bouncy radius, floating orbs',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'glow',
      'shader-glow-count': '12',
      'shader-glow-pulse': '0.5',
      'shader-glow-size': '0.7',
      'hero-glass-tint': '#FBBF24',
      'hero-border-tint': '#EC4899',
      'glass-tint': '#F9A8D4',
      'card-hover-scale': '1.05',
      'card-image-hover-scale': '1.1',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#EC4899',
      secondaryColor: '#F472B6',
      accentColor: '#FBBF24',
      backgroundColor: null,
      fontBody: 'Nunito',
      fontHeading: 'Fredoka',
      radius: 1.5,
      density: 1.05,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#F9A8D4',
      },
    },
  },
  {
    id: 'retro',
    name: 'Retro',
    category: 'Playful',
    description: 'Throwback vibes — orange zest, cream canvas, film grain',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'film',
      'shader-film-speed': '0.3',
      'shader-film-bands': '0.4',
      'heading-color': '#9A3412',
      'hero-glass-tint': '#FBBF24',
      'hero-border-tint': '#EA580C',
      'glass-tint': '#FBBF24',
      'card-hover-scale': '1.03',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#EA580C',
      secondaryColor: '#DC2626',
      accentColor: '#FBBF24',
      backgroundColor: '#FFFBEB',
      fontBody: 'Space Grotesk',
      fontHeading: 'Archivo Black',
      radius: 0.75,
      density: 1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#FB923C',
        backgroundColor: '#1A1207',
      },
    },
  },
  {
    id: 'arcade',
    name: 'Arcade',
    category: 'Playful',
    description: 'Game on — bright blue, lime accents, plasma energy',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'plasma',
      'shader-plasma-speed': '0.5',
      'shader-plasma-bands': '0.6',
      'heading-color': '#3B82F6',
      'hero-title-blend': 'normal',
      'hero-title-color': '#60A5FA',
      'hero-glass-tint': '#A3E635',
      'hero-border-tint': '#3B82F6',
      'player-text': '#60A5FA',
      'glass-tint': '#A3E635',
      'card-hover-scale': '1.05',
      'card-image-hover-scale': '1.1',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#3B82F6',
      secondaryColor: '#A3E635',
      accentColor: '#F472B6',
      backgroundColor: '#0F172A',
      fontBody: 'Space Grotesk',
      fontHeading: 'Space Grotesk',
      radius: 0.5,
      density: 0.95,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#60A5FA',
        backgroundColor: '#080E1F',
      },
    },
  },

  // ─── Atmospheric ────────────────────────────────────────────────────
  {
    id: 'midnight',
    name: 'Midnight',
    category: 'Atmospheric',
    description: 'Deep blue twilight — silver accents, aurora shimmer',
    heroLayout: 'centered',
    tokenOverrides: {
      'shader-preset': 'aurora',
      'shader-aurora-speed': '0.4',
      'shader-aurora-shimmer': '0.6',
      'heading-color': '#CBD5E1',
      'hero-glass-tint': '#38BDF8',
      'hero-border-tint': '#94A3B8',
      'glass-tint': '#94A3B8',
      'card-hover-scale': '1.02',
      'text-transform-label': 'capitalize',
    },
    values: {
      primaryColor: '#94A3B8',
      secondaryColor: '#64748B',
      accentColor: '#38BDF8',
      backgroundColor: '#0F172A',
      fontBody: 'Raleway',
      fontHeading: 'Raleway',
      radius: 0.5,
      density: 1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#CBD5E1',
        backgroundColor: '#0A0F1F',
      },
    },
  },
  {
    id: 'storm',
    name: 'Storm',
    category: 'Atmospheric',
    description: 'Electric intensity — dark clouds, lightning blue strikes',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'vortex',
      'shader-vortex-speed': '0.5',
      'shader-vortex-twist': '0.6',
      'heading-color': '#93C5FD',
      'hero-title-blend': 'normal',
      'hero-title-color': '#93C5FD',
      'hero-glass-tint': '#2563EB',
      'hero-border-tint': '#60A5FA',
      'glass-tint': '#2563EB',
      'card-hover-scale': '1.04',
      'card-image-hover-scale': '1.06',
      'text-transform-label': 'uppercase',
    },
    values: {
      primaryColor: '#2563EB',
      secondaryColor: '#1D4ED8',
      accentColor: '#FBBF24',
      backgroundColor: '#1F2937',
      fontBody: 'DM Sans',
      fontHeading: 'DM Sans',
      radius: 0.375,
      density: 1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#60A5FA',
        backgroundColor: '#111827',
      },
    },
  },
  {
    id: 'zen',
    name: 'Zen',
    category: 'Atmospheric',
    description: 'Gentle calm — warm white, sage green, gentle rain',
    heroLayout: 'default',
    tokenOverrides: {
      'shader-preset': 'rain',
      'shader-rain-speed': '0.3',
      'shader-rain-density': '0.3',
      'heading-color': '#5F7A63',
      'hero-glass-tint': '#8FAE92',
      'hero-border-tint': '#6B8F71',
      'glass-tint': '#8FAE92',
      'card-hover-scale': '1.01',
      'card-image-hover-scale': '1.02',
      'text-transform-label': 'none',
    },
    values: {
      primaryColor: '#6B8F71',
      secondaryColor: '#8FAE92',
      accentColor: '#D4A843',
      backgroundColor: '#FEFCE8',
      fontBody: 'Lora',
      fontHeading: 'Lora',
      radius: 0.75,
      density: 1.1,
      heroLayout: 'default',
      darkOverrides: {
        primaryColor: '#8FAE92',
        backgroundColor: '#1A1A0E',
      },
    },
  },
] as const;
