export const ERROR_CODES = {
  INVALID_URL: 'INVALID_URL',
  SSRF_BLOCKED: 'SSRF_BLOCKED',
  HTTPS_REQUIRED: 'HTTPS_REQUIRED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  R2_SIGNING_ERROR: 'R2_SIGNING_ERROR',
  INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
  ORGANIZATION_MISMATCH: 'ORGANIZATION_MISMATCH',
  MEDIA_NOT_READY: 'MEDIA_NOT_READY',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
} as const;

export const STATUS_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_ERROR: 500,
} as const;

export const AWS_ERRORS = {
  NOT_FOUND: 'NotFound',
} as const;

export class UrlValidationError extends Error {
  constructor(
    message: string,
    public code: keyof typeof ERROR_CODES
  ) {
    super(message);
    this.name = 'UrlValidationError';
  }
}
