-- Codex-ppxtd (WP-1 of Codex-nk4km) — backfill negotiation history for
-- pre-existing creator_organization_agreements rows.
--
-- After 0071, every existing row already has revenue_type='subscription'
-- and status='active' (column defaults). This migration synthesises one
-- 'accepted' agreement_proposals row per existing agreement so that the
-- service layer (WP-2+) can assume `current_proposal_id` is always set on
-- an active agreement.
--
-- Semantics of the synthesised proposal:
--   round_number = 1 (initial offer)
--   proposed_by_role = 'owner'
--   proposed_by_user_id = the org's owner, resolved as the user with
--     organization_memberships.role='owner' AND status='active'. If the org
--     has no active owner membership (edge case for orphaned orgs) we fall
--     back to the agreement's own creator_id — the row is still useful as
--     historical record and the WP-2 service will treat 'creator'-authored
--     accepted-at-round-1 proposals as legacy backfill rows.
--   proposed_creator_share_percent = derived from the legacy
--     `organization_fee_percentage` column. The legacy column stored the
--     ORG's cut of post-platform-fee revenue, so the CREATOR's share is
--     10000 - organization_fee_percentage (basis points).
--   proposed_effective_from = the agreement's effective_from
--   status = 'accepted', responded_at = created_at, responded_by_user_id
--     = the same resolved owner (the same actor who'd have accepted their
--     own offer under the legacy single-side model).
--
-- Two write steps in one statement:
--   (1) INSERT one proposal per agreement.
--   (2) UPDATE agreements.current_proposal_id from the synthesised rows.
--
-- The CTE approach keeps the mapping in a single statement so re-running
-- the migration over a partial state is impossible — agreement_proposals
-- IDs are generated by gen_random_uuid() at INSERT time and immediately
-- captured.

WITH inserted AS (
  INSERT INTO "agreement_proposals" (
    "organization_id",
    "creator_id",
    "revenue_type",
    "parent_proposal_id",
    "round_number",
    "proposed_by_user_id",
    "proposed_by_role",
    "proposed_creator_share_percent",
    "proposed_term_months",
    "proposed_effective_from",
    "note",
    "status",
    "responded_at",
    "responded_by_user_id",
    "decline_reason",
    "created_at",
    "updated_at"
  )
  SELECT
    a."organization_id",
    a."creator_id",
    a."revenue_type",
    NULL::uuid,
    1,
    COALESCE(owner_m."user_id", a."creator_id"),
    'owner',
    10000 - a."organization_fee_percentage",
    NULL::integer,
    a."effective_from",
    'Backfilled from pre-WP-1 agreement (Codex-ppxtd).',
    'accepted',
    a."created_at",
    COALESCE(owner_m."user_id", a."creator_id"),
    NULL::text,
    a."created_at",
    a."created_at"
  FROM "creator_organization_agreements" a
  LEFT JOIN LATERAL (
    SELECT m."user_id"
    FROM "organization_memberships" m
    WHERE m."organization_id" = a."organization_id"
      AND m."role" = 'owner'
      AND m."status" = 'active'
    ORDER BY m."created_at" ASC
    LIMIT 1
  ) owner_m ON true
  WHERE a."current_proposal_id" IS NULL
    AND a."status" = 'active'
  RETURNING
    "id" AS proposal_id,
    "organization_id",
    "creator_id",
    "revenue_type",
    "proposed_effective_from"
)
UPDATE "creator_organization_agreements" a
SET "current_proposal_id" = i.proposal_id
FROM inserted i
WHERE a."organization_id" = i."organization_id"
  AND a."creator_id" = i."creator_id"
  AND a."revenue_type" = i."revenue_type"
  AND a."effective_from" = i."proposed_effective_from"
  AND a."status" = 'active'
  AND a."current_proposal_id" IS NULL;
