name = "queue-consumer"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Queue bindings
[[queues.consumers]]
queue = "media-processing-queue"
max_batch_size = 10
max_batch_timeout = 30

# Environment variables
[env.development]
name = "queue-consumer-dev"

[env.production]
name = "queue-consumer-prod"
