import type { StyleDefinition } from '../style-definition';

export const CINEMATIC: StyleDefinition = {
  id: 'cinematic',
  label: 'Cinematic',
  description:
    'Dark and immersive, with full-width imagery and a glow of your brand colour.',
  layouts: {
    hero: 'cover',
    video: 'theatre',
    problem: 'statement',
    story: 'scroll',
    transformation: 'statement',
    benefits: 'split',
    curriculum: 'timeline',
    preview: 'feature',
    gallery: 'strip',
    instructor: 'quote',
    testimonials: 'quote',
    faq: 'accordion',
    pricing: 'focus',
    cta: 'band',
    stats: 'row',
    text: 'statement',
  },
  // Cinematic's base is dark in both themes; the lifted tint is its only
  // variation, so the page reads as one continuous dark room.
  schemes: {
    hero: 'base',
    video: 'soft',
    problem: 'base',
    story: 'base',
    text: 'base',
    transformation: 'soft',
    benefits: 'base',
    curriculum: 'soft',
    preview: 'base',
    gallery: 'soft',
    instructor: 'soft',
    testimonials: 'base',
    stats: 'soft',
    pricing: 'base',
    faq: 'soft',
    cta: 'base',
  },
  featured: {
    base: 'soft',
    soft: 'base',
    contrast: 'brand',
    brand: 'base',
    accent: 'base',
    atmosphere: 'soft',
  },
  order: [
    'hero',
    'video',
    'problem',
    'story',
    'transformation',
    'preview',
    'gallery',
    'text',
    'curriculum',
    'benefits',
    'instructor',
    'testimonials',
    'stats',
    'pricing',
    'faq',
    'cta',
  ],
  starter: [
    'hero',
    'video',
    'problem',
    'transformation',
    'curriculum',
    'instructor',
    'testimonials',
    'pricing',
    'faq',
    'cta',
  ],
};
