import { STORY_ORDER, type StyleDefinition } from '../style-definition';

export const CLEAN: StyleDefinition = {
  id: 'clean',
  label: 'Clean',
  description:
    'Crisp and image-led with plenty of space. Lets your photos breathe.',
  layouts: {
    hero: 'split',
    video: 'split',
    problem: 'list',
    story: 'strip',
    transformation: 'steps',
    benefits: 'grid',
    curriculum: 'accordion',
    preview: 'split',
    gallery: 'grid',
    instructor: 'split',
    testimonials: 'grid',
    faq: 'accordion',
    pricing: 'cards',
    cta: 'split',
    stats: 'grid',
    text: 'columns',
  },
  // Strict base / tint alternation, closing on one contrast band so the last
  // ask does not read as another content section.
  schemes: {
    hero: 'base',
    video: 'soft',
    problem: 'base',
    story: 'base',
    text: 'soft',
    transformation: 'base',
    benefits: 'soft',
    curriculum: 'base',
    preview: 'soft',
    gallery: 'base',
    instructor: 'base',
    testimonials: 'soft',
    stats: 'base',
    pricing: 'soft',
    faq: 'base',
    cta: 'contrast',
  },
  featured: {
    base: 'contrast',
    soft: 'base',
    contrast: 'base',
    brand: 'base',
    accent: 'base',
    atmosphere: 'base',
  },
  order: STORY_ORDER,
  starter: [
    'hero',
    'transformation',
    'benefits',
    'curriculum',
    'instructor',
    'testimonials',
    'stats',
    'pricing',
    'faq',
    'cta',
  ],
  // A neutral grotesk pair (03 §4.1). Provisional, from E5, so the Style tab's
  // suggestion can be seen; Clean's Style WP chooses the final pair.
  fonts: { heading: 'Manrope', body: 'Inter' },
};
