import { STORY_ORDER, type StyleDefinition } from '../style-definition';

export const SOFT: StyleDefinition = {
  id: 'soft',
  label: 'Soft',
  description: 'Rounded shapes and gentle tints. Calm, warm and welcoming.',
  layouts: {
    hero: 'centered',
    video: 'theatre',
    problem: 'split',
    story: 'strip',
    transformation: 'columns',
    benefits: 'grid',
    curriculum: 'cards',
    preview: 'split',
    gallery: 'mosaic',
    instructor: 'centered',
    testimonials: 'grid',
    faq: 'accordion',
    pricing: 'cards',
    cta: 'band',
    stats: 'grid',
    text: 'centered',
  },
  // Tint first, then page: the tint is Soft's ground and the plain bands are
  // the pauses. It closes warm, on the brand colour.
  schemes: {
    hero: 'soft',
    video: 'base',
    problem: 'soft',
    story: 'base',
    text: 'base',
    transformation: 'soft',
    benefits: 'base',
    curriculum: 'soft',
    preview: 'base',
    gallery: 'base',
    instructor: 'soft',
    testimonials: 'base',
    stats: 'soft',
    pricing: 'base',
    faq: 'soft',
    cta: 'brand',
  },
  featured: {
    base: 'soft',
    soft: 'base',
    contrast: 'soft',
    brand: 'base',
    accent: 'base',
    atmosphere: 'base',
  },
  order: STORY_ORDER,
  starter: [
    'hero',
    'problem',
    'transformation',
    'benefits',
    'curriculum',
    'instructor',
    'testimonials',
    'pricing',
    'faq',
    'cta',
  ],
};
