name: Deploy Workers

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy-workers:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest
    # Only deploy if tests pass
    needs: []  # Will be updated to depend on test workflow when needed

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy queue-consumer worker
        run: pnpm --filter queue-consumer deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy webhook-handler worker
        run: pnpm --filter webhook-handler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deployment notification
        if: success()
        run: echo "✅ Workers deployed successfully to production"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Worker deployment failed - check logs"
